version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=imdb_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - imdb_network

  web:
    container_name: imdbreview
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - imdb_network

networks:
  imdb_network:
