version: "3.9"

services:
  db:
    image: postgres
    # ports:
    #   - "5432:5432"
    environment:
      # - PGHOST=host.docker.internal
      # - PGPORT=5432
      # - PGUSER=postgres
      - POSTGRES_DB=imdblocal
      - POSTGRES_USER=samruddhi
      - POSTGRES_PASSWORD=sam@123
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - IMDBdbmdp_services

  web:
    container_name: imdbreview
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - IMDBdbmdp_services

networks:
  IMDBdbmdp_services: